#+title: uni fep benchmarks cofolding

OpenFold3 structure generation for the Uni FEP Benchmark sets.

The master set of queries is held in =data/= and is used to generate
individual data sets with the =results/= directory.

** Generating dataset inputs

With pixi installed, generate the dataset inputs with: 

#+BEGIN_SRC bash
pixi run python3 run.py
#+END_SRC

** =openfold3= setup

Execution logic is held in the =Makefile= in the root of the
project. Since the openfold3 environment is fragile, we run each job
through their isolated pixi environments.

Set the following Makefile macros for things to just work™.

- =CUDA_MAJOR_VERSION=
- =PIXI=
- =OPENFOLD3_REPO=

If you haven't used the openfold3 environment yet, run =make setup=
and follow the prompts that will download the checkpoints. This will
also give you the opportunity to run openfold-3 integration tests.

** Running datasets

In the underlying results directory for your dataset, run:

#+BEGIN_SRC bash
make -f ../../Makefile run-cli
#+END_SRC

If using SLURM, you can use the provided submission script,
=submit.slurm= or provide your own. From the run directory run ~sbatch ../../submit.slurm~.
